# 예외 종류에 따른 처리 코드
## 다중 catch
- try 블록 내부에서 다양한 종류의 예외가 발생할 수 있기 때문에 catch 블록을 여러 개 작성해서 여러 개의 Exception을 핸들링한다.
```aidl
try {
    // 실행 코드
} catch(ArrayIndexOutOfBoundsException e) {
    // 예외 처리 1
} catch(NumberFormatException e) {
    // 예외 처리 2
}
```
- catch 블록이 여러 개라 할지라도 단 하나의 catch 블록만 실행된다. 그 이유는 try 블록에서 동시다발적으로 예외가 발생하지 않고 하나의 예외가 발생하면 즉시 실행을 멈추고 해당 catch 블록으로 이동하기 때문이다.
## catch 순서
- 다중 catch 블록을 작성할 때 주의할 점은 상위 예외 클래스가 하위 예외 클래스보다 아래쪽에 위치해야한다.
```aidl
try {
    //ArrayIndexOutOfBoundsException 발생
} catch(Exception e) {
    //예외 처리 1
} catch(ArrayIndexOutOfBoundsException e) {  //실행되지 않는다.
    //예외 처리 2
}
```
## 멀티 catch
- 자바 7부터 하나의 catch 블록에서 여러 개의 예외를 처리할 수 있도록 멀티 catch 기능을 추가했다.
- catch 괄호 안에 동일하게 처리하고 싶은 예외를 | 로 연결하면 된다.
```aidl
try {
    //ArrayIndexOutOfBoundsException 또는 NumberFormatException 발생
} catch(ArrayIndexOutOfBoundsException | NumberFormatException e) {
    //예외 처리
}
```
## 자동 리소스 닫기
- try-with-resources를 사용하면 예외 발생 여부와 상관없이 사용했던 리소스 객체(각종 입출력 스트림, 서버 소켓, 소켓, 각종 채널)의 close() 메소드를 호출해서 안전하게 리소스를 닫아준다.
```aidl
try(FileInputStream fis = new FileInputStream("file.txt")) {
    ...
} catch(IOException e) {
    ...
}
```
- try 블록이 정상적으로 실행을 완료했거나 도중에 예외가 발생하게 되면 자동으로 FileInputStream의 close()메소드가 호출된다.
    - 예외가 발생하면 우선 close()로 리소스를 닫고 catch 블록을 실행한다.
    
**복수 개의 리소스 사용 예**
```aidl
    try(
      FileInputStream fis = new FileInputStream("file1.txt");
      FileOutputStream fos = new FileOutputStream("file2.txt");
    ) {
        ...
    } catch(IOException e) {
        ...
    }
```
- try-with-resources를 사용하기 위해서는 리소스 객체가 java.lang.AutoCloseable 인터페이스를 구현하고 있어야한다. AutoCloseable에는 close() 메소드가 정의되어 있는데 이 메소드를 호출하기 때문이다.
- APi 도큐먼트에서 AutoCloseable 인터페이스를 찾아 "All Known Implemeting Classes"를 보면 사용할 수 있는 리소스가 어떤 것이 있는지 알 수 있다.
## 예외 떠넘기기
- 메소드 내부에서 예외가 발생할 수 있는 코드를 작성할 때 try-catch 블록으로 예외를 처리하는 것이 기본이지만, 경우에 따라서는 메소드를 호출한 곳으로 예외를 떠넘길 수도 있다.
- 이때 throws 라는 키워드를 사용한다.
```aidl
리턴타입 메소드명(매개변수, ...) throws 예외클래스1, 예외클래스2, ... {
}
```
- 발생할 수 있는 예외의 종류별로 throws 뒤에 나열하는 것이 일반적이지만, 다음과 같이 throws Exception만으로 모든 예외를 간단히 떠넘길 수도 있다.
```aidl
리턴타입 메소드명(매개변수, ...) throws Exception {
}
```
- throws 키워드가 붙어있는 메소드는 반드시 try 블록 내에서 호출되어야한다. 그리고 catch 블록에서 떠넘겨 받은 예외를 처리해야 한다.
## 사용자 정의 예외와 예외 발생
- 프로그램을 개발하다 보면 자바 표준 API에서 제공하는 예외 클래스만으로는 다양한 종류의 예외를 표현할 수가 없다.
- 이런 예외들을 처리하는 예외를 애플리케이션 예외(Application Exception)라고 한다. 애플리케이션 예외는 개발자가 직접 정의해서 만들어야 하므로 사용자 정의 예외라고도 한다. 