# 예외 처리 코드
- 프로그램에서 예외가 발생했을 경우 프로그램의 갑작스러운 종료를 막고, 정상 실행을 유지할 수 있도록 처리하는 코드를 예외 처리 코드라고 한다.
- 자바 컴파일러는 컴파일할 때 일반 예외가 발생할 가능성이 있는 코드를 발견하면 컴파일 오류를 발생시켜 개발자로 하여금 강제적으로 예외 처리 코드를 작성하도록 요구한다.
- 하지만 실행 예외는 컴파일러가 체크해주지 않기 때문에 예외 처리 코드를 작성해야한다.
- 예외 처리 코드는 try-catch-finally 블록을 이용한다.
- ArrayIndexOutOfBoundsException이나 NumberFormatException과 같은 실행 예외는 컴파일러가 예외 처리 코드를 체크하지 않기 때문에 빨간 밑줄이 생기지 않는다. 오로지 개발자의 경험에 의해 예외 처리를 작성해줘야한다.
## try-catch-finally
- 생성자 내부와 메소드 내부에서 작성되어 일반 예외와 실행 예외가 발생할 경우 예외 처리를 할 수 있도록 해준다.
- try-catch-finally 코드는 try 에서 코드를 실행하고 만약 거기서 예외가 발생하면 try 블록의 코드 실행을 멈추고 바로 catch 블록으로 넘어가 예외를 처리해준다. 그 뒤 finally를 실행한다.
- finally 블록은 옵션으로 생략 가능하다.
- try 블록과 catch 블록에서 return 문을 사용하더라도 finally 블록은 항상 실행된다.
```aidl
public class TryCatchFinallyExample {
    public static void main(String[] args) {
        try {
            Class clazz = Class.forName("java.lang.String2");  //ClassCastException 발생
        } catch(ClassNotFoundException e) {
            System.out.println("클래스가 존재하지 않습니다.");
        }
    }
}
```
### 실행 예외 처리 예
```aidl
public class TryCatchFinallyRuntimeExceptionExample {
    public static void main(String[] args) {
        String data1 = null;
        String data2 = null;
        try {
            data1 = args[0];
            data2 = args[1];
        } catch(ArrayIndexOutOfBoundsException e) {
            System.out.println("실행 매개값의 수가 부족합니다.");
            System.out.println("[실행 방법]");
            System.oout.println("java TryCatchFinallyRuntimeException Example num1 num2");
            return;
        }
        try {
            int value1 = Integer.parseInt(data1);
            int value2 = Integer.parseInt(data2);
            int result = value1 + value2;
            System.out.println(data1 + "+" + data2 + "=" + result);
        } catch(NumberFormatException e) {
            System.out.println("숫자로 변환할 수 없습니다.");
        } finally {
            System.out.println("다시 실행하세요");
        }
    }
}
```